const database = [
    {
     "idProduct": 1,
     "brand ": "festina ",
     "model": "F16601\/3",
     "style ": "clasico",
     "color": "black",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/F16601-3.jpg",
     "strap": "goma ",
     "price ": 345,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "luz, sumergible, gps",
     "description": "diseño distinguido"
    },
    {
     "idProduct": 2,
     "brand ": "festina ",
     "model": "F20511\/3",
     "style ": "clasico",
     "color": "blue ",
     "image": "https:\/\/static6.festinagroup.com\/product\/festina\/watches\/detail\/f20511_3.webp",
     "strap": "acero",
     "price ": 85,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "analógico, calendario, estanqueidad",
     "description": "sinonimo de durabilidad y resistencia "
    },
    {
     "idProduct": 3,
     "brand ": "festina ",
     "model": "F16719\/1",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/festina-f16719-1.jpg",
     "strap": "metal",
     "price ": 125,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "luz, sumergible, gps",
     "description": "elegancia y funcionalidad "
    },
    {
     "idProduct": 4,
     "brand ": "festina ",
     "model": "F16834\/1",
     "style ": "clasico",
     "color": "black",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/F16834-1-1.jpg",
     "strap": "goma ",
     "price ": 194,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma, resistencia al agua, bisel giratorio",
     "description": "mezcla perfecta de elegancia y funcionalidad"
    },
    {
     "idProduct": 5,
     "brand ": "festina ",
     "model": "F16867\/2",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/F16867-2-1.jpg",
     "strap": "metal ",
     "price ": 129,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "alarma, cronometro, indicadores luminosos",
     "description": "alta precision "
    },
    {
     "idProduct": 6,
     "brand ": "festina ",
     "model": "F16526\/6",
     "style ": "deportivo",
     "color": "black",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/Festina-F16526-6-Stainless-Steel-Watch_1_104_0.jpg",
     "strap": "goma ",
     "price ": 262,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "analógico, calendario, estanqueidad",
     "description": "diseño elegante y alta durabilidad "
    },
    {
     "idProduct": 7,
     "brand ": "festina ",
     "model": "F16574\/2",
     "style ": "deportivo",
     "color": "orange ",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/reloj-festina-caballero-f16574-2.jpg",
     "strap": "plastico",
     "price ": 214,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma, cronometro, indicadores luminosos",
     "description": "variedad de modelos y precisión"
    },
    {
     "idProduct": 8,
     "brand ": "festina ",
     "model": "F16656\/1",
     "style ": "clasico",
     "color": "golden",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/F16656-1.jpg",
     "strap": "metal",
     "price ": 370,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma, cronometro, indicadores luminosos",
     "description": "variedad de modelos y precisión"
    },
    {
     "idProduct": 9,
     "brand ": "festina ",
     "model": "F16940\/1",
     "style ": "clasico",
     "color": "silver",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/f16940-1.jpg",
     "strap": "metal",
     "price ": 118,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "cronometro, alarma, bluetooth",
     "description": "alta precision "
    },
    {
     "idProduct": 10,
     "brand ": "festina ",
     "model": "F20223\/2",
     "style ": "clasico",
     "color": "silver",
     "image": "https:\/\/pipol.com.py\/wp-content\/uploads\/F20223-2.jpg",
     "strap": "metal",
     "price ": 128,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "alarma, cronometro, indicadores luminosos",
     "description": "sinonimo de durabilidad y resistencia "
    },
    {
     "idProduct": 11,
     "brand ": "mistral",
     "model": "cht-7263S-2b",
     "style ": "clasico",
     "color": "blue ",
     "image": "https:\/\/tinyurl.com\/RELOJ-MISTRAL-CHT-7263S-2B ",
     "strap": "acero",
     "price ": 320,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "cronografo, cronometro, sumergible",
     "description": "sumergible y analogico"
    },
    {
     "idProduct": 12,
     "brand ": "mistral",
     "model": "gsi-2133-08",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/158120-800-800",
     "strap": "acero",
     "price ": 285,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "analogo,calendario, sumergible",
     "description": "puntero analogico y sumergible "
    },
    {
     "idProduct": 13,
     "brand ": "mistral",
     "model": "gmt-6075-7a",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/157466-800-800",
     "strap": "acero",
     "price ": 250,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "analogo,sumergible",
     "description": "analogico y resistente al agua "
    },
    {
     "idProduct": 14,
     "brand ": "mistral",
     "model": "chi-2026-07",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/165453-800-800",
     "strap": "acero",
     "price ": 285,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "analogo, cronografo, cronometro",
     "description": "cuadrante blanco con textura, detalles en nickel"
    },
    {
     "idProduct": 15,
     "brand ": "mistral",
     "model": "ldx-ban-04",
     "style ": "clasico",
     "color": "pink",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/160166-800-800",
     "strap": "silicona ",
     "price ": 200,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "cuenta regresiva, calendario, cronometo",
     "description": "digital,pulsadores de metal,malla de silicona "
    },
    {
     "idProduct": 16,
     "brand ": "mistral",
     "model": "lax-wu-04",
     "style ": "clasico",
     "color": "violet",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/164713-800-800",
     "strap": "silicona ",
     "price ": 190,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "analogo,luz, sumergible",
     "description": "reloj análogo, caja de plástico, aro metálico"
    },
    {
     "idProduct": 17,
     "brand ": "mistral",
     "model": "lmi-1036-04",
     "style ": "clasico",
     "color": "golden",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/163287-800-800",
     "strap": "acero",
     "price ": 260,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "analogo, sumergible",
     "description": "reloj análogo, caja de plástico, aro metálico"
    },
    {
     "idProduct": 18,
     "brand ": "mistral",
     "model": "smt-x29-01",
     "style ": "smart",
     "color": "black",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/164420-800-800",
     "strap": "plastico",
     "price ": 310,
     "gender ": "unisex",
     "   reviews": 0,
     "function": "gps, alarma, bluetooth, frecuencia cardiaca",
     "description": "reloj smart con gps incorporado"
    },
    {
     "idProduct": 19,
     "brand ": "mistral",
     "model": "smt-gtm5-03 ",
     "style ": "smart",
     "color": "green",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/164598-1200-1200",
     "strap": "silicona ",
     "price ": 350,
     "gender ": "unisex",
     "   reviews": 0,
     "function": "analogo,luz, sumergible",
     "description": "puntero analogico y sumergible "
    },
    {
     "idProduct": 20,
     "brand ": "mistral",
     "model": "smt-ts67-09",
     "style ": "smart",
     "color": "golden",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/165567-800-800 ",
     "strap": "plastico",
     "price ": 230,
     "gender ": "unisex",
     "   reviews": 0,
     "function": "cronometro, alarma, bluetooth",
     "description": "malla de metal tejido intercambiable"
    },
    {
     "idProduct": 21,
     "brand ": "mistral",
     "model": "gax-caf-03",
     "style ": "deportivo",
     "color": "green",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/164737-800-800",
     "strap": "plastico",
     "price ": 215,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma, cronometo, calendario luz",
     "description": "analogo,luz, sumergible"
    },
    {
     "idProduct": 22,
     "brand ": "mistral",
     "model": "lax-aal-04",
     "style ": "deportivo",
     "color": "pink",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/160186-800-800",
     "strap": "silicona ",
     "price ": 100,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "analogo, sumergible, luz",
     "description": "variedad de modelos y precisión"
    },
    {
     "idProduct": 23,
     "brand ": "casio",
     "model": "ECB-2000PB-1A",
     "style ": "deportivo",
     "color": "black",
     "image": "http:\/\/bit.ly\/Reloj-Casio-Edifice-ECB-2000PB-1A-Sospensione",
     "strap": "resina ",
     "price ": 150,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "iluminacion led, temporizador, cronometro",
     "description": "Inspirado en la suspensión de los automóviles de formula"
    },
    {
     "idProduct": 24,
     "brand ": "casio",
     "model": "EDIFICE ECB-2000MFG-1A",
     "style ": "deportivo",
     "color": "red",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/165743-800-800",
     "strap": "cuero",
     "price ": 175,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma,analogo,digital",
     "description": "elaboración limitada "
    },
    {
     "idProduct": 25,
     "brand ": "casio",
     "model": "edifice EFV-C110L-1A",
     "style ": "deportivo",
     "color": "black",
     "image": "https:\/\/d3ugyf2ht6aenh.cloudfront.net\/stores\/001\/417\/925\/products\/imagen_2023-01-04_0959004771-17d5479246b4bbf82016728371759372-640-0.webp",
     "strap": "cuero",
     "price ": 180,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "cronometro, alarma, bluetooth",
     "description": "aspecto deportivo y dinamico"
    },
    {
     "idProduct": 26,
     "brand ": "casio",
     "model": "edifice EFV-140D-2A",
     "style ": "urbano",
     "color": "grey",
     "image": "https:\/\/d3ugyf2ht6aenh.cloudfront.net\/stores\/001\/417\/925\/products\/imagen_2022-07-20_1408143421-5d8391c1c7e82e7fbf16583369130230-640-0.webp",
     "strap": "acero",
     "price ": 155,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "pantalla de fecha, alarma, cronometro",
     "description": "version simple y deportiva "
    },
    {
     "idProduct": 27,
     "brand ": "casio",
     "model": "VINTAGE A-168WEMB-1B",
     "style ": "vintage ",
     "color": "black",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/164359-800-800",
     "strap": "acero",
     "price ": 185,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "iluminacion led, temporizador, cronometro",
     "description": "aspecto deportivo y dinamico"
    },
    {
     "idProduct": 28,
     "brand ": "casio",
     "model": "VINTAGE A-168WEGC-3D",
     "style ": "vintage ",
     "color": "golden",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/155633-1600-1600",
     "strap": "acero",
     "price ": 177,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma,digital,calendario",
     "description": "cronometro y iluminacion led"
    },
    {
     "idProduct": 29,
     "brand ": "casio",
     "model": "VINTAGE B-640WC-5A",
     "style ": "vintage ",
     "color": "pink",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/157080-800-800",
     "strap": "acero",
     "price ": 178,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "cuenta regresiva, calendario, cronometo",
     "description": "aspecto deportivo y dinamico"
    },
    {
     "idProduct": 30,
     "brand ": "casio",
     "model": "VINTAGE CA-53FB-1B",
     "style ": "vintage ",
     "color": "black",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/162375-1600-1600",
     "strap": "plastico",
     "price ": 245,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "iluminacion led, temporizador, cronometro",
     "description": "elaboración limitada "
    },
    {
     "idProduct": 31,
     "brand ": "casio",
     "model": "EDIFICE ECB-10TMS-1A",
     "style ": "deportivo",
     "color": "black",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/160106-800-800",
     "strap": "resina ",
     "price ": 345,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "alarma, cronometro, cuenta regresiva ",
     "description": "edicion limitada"
    },
    {
     "idProduct": 32,
     "brand ": "casio",
     "model": "EDIFICE EQB-1000HR-1A",
     "style ": "deportivo",
     "color": "black",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/160673-800-800",
     "strap": "acero",
     "price ": 280,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "cuenta regresiva, calendario, cronometo",
     "description": "aspecto deportivo y dinamico"
    },
    {
     "idProduct": 33,
     "brand ": "casio",
     "model": "MQ-24S-4B",
     "style ": "standard",
     "color": "gray",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/165973-800-800",
     "strap": "plastico",
     "price ": 357,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "alarma,digital,calendario",
     "description": "resistente al agua y caja metalizada"
    },
    {
     "idProduct": 34,
     "brand ": "casio",
     "model": "LF-10WH-3D",
     "style ": "standard",
     "color": "pink",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/165959-800-800",
     "strap": "biomasa",
     "price ": 189,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "alarma, cronometro,luz ",
     "description": "luz led con persistencia luminosa "
    },
    {
     "idProduct": 35,
     "brand ": "casio",
     "model": "MTP-E710M-1A",
     "style ": "standard",
     "color": "blue ",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/165977-800-800",
     "strap": "acero",
     "price ": 196,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "analogo,calendario, sumergible",
     "description": "malla de metal tejido intercambiable"
    },
    {
     "idProduct": 36,
     "brand ": "casio",
     "model": "LTP-B115D-4E",
     "style ": "standard",
     "color": "pink",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/163707-1600-1600",
     "strap": "acero",
     "price ": 179,
     "gender ": "caballero ",
     "   reviews": 0,
     "function": "iluminacion led, temporizador, cronometro",
     "description": "baño de iones en negro"
    },
    {
     "idProduct": 37,
     "brand ": "casio",
     "model": "LTP-V005GL-7B",
     "style ": "standard",
     "color": "white",
     "image": "https:\/\/watchlandsa.vtexassets.com\/arquivos\/ids\/156499-800-800",
     "strap": "cuero",
     "price ": 200,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "analogo",
     "description": "resistente al agua y caja metalizada"
    },
    {
     "idProduct": 38,
     "brand ": "citizen",
     "model": "ECO-DRIVE ",
     "style ": "clasico",
     "color": "golden",
     "image": "https:\/\/citizen.es\/wp-content\/uploads\/2021\/07\/EM0493-85P.jpg",
     "strap": "acero",
     "price ": 350,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "pantalla de fecha, alarma, cronometro",
     "description": "version simple y elegante "
    },
    {
     "idProduct": 39,
     "brand ": "citizen",
     "model": "EM0500-73A",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/citizen.es\/wp-content\/uploads\/2021\/07\/EM0500-73A.jpg",
     "strap": "acero",
     "price ": 280,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "alarma,cronometro",
     "description": "caja de acero con reserva de carga "
    },
    {
     "idProduct": 40,
     "brand ": "citizen",
     "model": "EM0504-81A",
     "style ": "clasico",
     "color": "grey",
     "image": "https:\/\/citizen.es\/wp-content\/uploads\/2021\/07\/EM0504-81A.jpg",
     "strap": "acero",
     "price ": 510,
     "gender ": "dama ",
     "   reviews": 0,
     "function": "iluminacion led, temporizador, cronometro",
     "description": "caja de acero con reserva de carga "
    }
   ];

   module.exports = database;